templates:
  chart_shared:
    default:
      collection_section: "00"
      key: <<collection_name>>
      sort: <<collection_name>>
      pre: "_"
      order_<<key>>: ""
      radarr_add_missing_<<key>>: <<radarr_add_missing>>
      sonarr_add_missing_<<key>>: <<sonarr_add_missing>>
      radarr_tag_<<key>>: <<radarr_tag>>
      sonarr_tag_<<key>>: <<sonarr_tag>>
      item_radarr_tag_<<key>>: <<item_radarr_tag>>
      item_sonarr_tag_<<key>>: <<item_sonarr_tag>>
    optional:
      - use_<<key>>
      - visible_library_<<key>>
      - visible_home_<<key>>
      - visible_shared_<<key>>
      - collection_mode
      - radarr_add_missing
      - sonarr_add_missing
      - radarr_tag
      - sonarr_tag
      - item_radarr_tag
      - item_sonarr_tag
      - library_types
      - check_library
    allowed_library_types:
      - <<use_<<key>>>>
      - <<check_library>>
    visible_library: <<visible_library_<<key>>>>
    visible_home: <<visible_home_<<key>>>>
    visible_shared: <<visible_shared_<<key>>>>
    radarr_add_missing: <<radarr_add_missing_<<key>>>>
    sonarr_add_missing: <<sonarr_add_missing_<<key>>>>
    radarr_tag: <<radarr_tag_<<key>>>>
    sonarr_tag: <<sonarr_tag_<<key>>>>
    item_radarr_tag: <<item_radarr_tag_<<key>>>>
    item_sonarr_tag: <<item_sonarr_tag_<<key>>>>
    collection_mode: hide
    sort_title: "!<<collection_section>><<pre>><<order_<<key>>>><<sort>>"
    url_poster: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager-Images/master/chart/<<collection_name_encoded>>.jpg
    schedule: weekly(sunday)
