external_templates:
  - repo: templates/collection_type/Collectionless_Label

collections:
  TV Source__bluray:
    template:
      - name: TMDB source label
        source_type: bluray
    plex_search:
      any:
        label:
          - ID__000100088A # The Last of Us (2023)
          - ID__000046648A # True Detective (2014)
