libraries:
  Movies:
    operations:
      assets_for_all: true
      content_rating_mapper:
        "gb/12A": "gb/12"
        None: "gb/Unrated"
      genre_mapper:
        Biography: Biopic
        "Sci-Fi": Science Fiction
        Martial Arts:
        Western:
    metadata_path:
      - repo: metadata/Ant-Man and the Wasp (2018) {tmdb-363088}
      - repo: metadata/Avengers Endgame (2019) {tmdb-299534}
      - repo: metadata/Captain America The First Avenger (2011) {tmdb-1771}
      - repo: metadata/Captain Marvel (2019) {tmdb-299537}
      - repo: metadata/Doctor Strange (2016) {tmdb-284052}
      - repo: metadata/Pirates of the Caribbean Dead Men Tell No Tales (2017) {tmdb-166426}
      - repo: metadata/Spider-Man Far from Home (2019) {tmdb-429617}
      - repo: metadata/Star Wars (1977) {tmdb-11}
      - repo: metadata/The Usual Suspects (1995) {tmdb-629}
      - repo: labelling/movies/editions
      - repo: labelling/movies/ownership
      - repo: labelling/movies/restrictions
      - repo: labelling/movies/series
      - repo: labelling/movies/sources
      - repo: labelling/shared/themes
      - repo: labelling/movies/themes
      - repo: libraries/shared/actors
      - repo: libraries/movies/directors
      - repo: libraries/movies/general
      - repo: libraries/shared/content_ratings
      - repo: libraries/movies/editions
      - repo: libraries/movies/editions_metadata
      - repo: libraries/shared/genres
      - repo: libraries/shared/series
      - repo: libraries/movies/series
      - repo: libraries/shared/themes
      - repo: libraries/movies/themes
      - repo: libraries/movies/charts
  TV shows:
    operations:
      assets_for_all: true
      content_rating_mapper:
        "gb/12A": "gb/12"
      genre_mapper:
        Biography: Biopic
        "Sci-Fi": Science Fiction
        Martial Arts:
        Western:
    metadata_path:
      - repo: labelling/tv_shows/content/drug_references
      - repo: labelling/tv_shows/content/drug_use
      - repo: labelling/tv_shows/content/gore
      - repo: labelling/tv_shows/content/horror
      - repo: labelling/tv_shows/content/injury_detail
      - repo: labelling/tv_shows/content/language
      - repo: labelling/tv_shows/content/nudity
      - repo: labelling/tv_shows/content/sex_references
      - repo: labelling/tv_shows/content/sex
      - repo: labelling/tv_shows/content/sexual_violence
      - repo: labelling/tv_shows/content/suicide
      - repo: labelling/tv_shows/content/threat
      - repo: labelling/tv_shows/content/violence
      - repo: labelling/tv_shows/ownership
      - repo: labelling/tv_shows/sources
      - repo: labelling/tv_shows/themes
      - repo: labelling/shared/themes
      - repo: libraries/shared/actors
      - repo: libraries/shared/content_ratings
      - repo: libraries/shared/genres
      - repo: libraries/shared/series
      - repo: libraries/shared/themes
      - repo: libraries/tv_shows/themes
  Stand-up comedy:
    operations:
      assets_for_all: true
    metadata_path:
      - repo: libraries/shared/content_ratings
  Short films:
    operations:
      assets_for_all: true
      content_rating_mapper:
        "gb/12A": "gb/12"
        None: "gb/Unrated"
      genre_mapper:
        Biography: Biopic
        "Sci-Fi": Science Fiction
        Martial Arts:
        Short:
        Western:
    metadata_path:
      - repo: labelling/short_films/ownership
      - repo: labelling/short_films/restrictions
      - repo: labelling/short_films/series
      - repo: labelling/short_films/sources
      - repo: labelling/short_films/themes
      - repo: libraries/shared/actors
      - repo: libraries/short_films/series
      - repo: libraries/short_films/themes
  Documentaries:
    operations:
      assets_for_all: true
      content_rating_mapper:
        "gb/12A": "gb/12"
      genre_mapper:
        Biography: Biopic
        "Sci-Fi": Science Fiction
        Martial Arts:
        Western:
    metadata_path:
      - repo: labelling/documentaries/themes
      - repo: libraries/shared/content_ratings
      - repo: libraries/shared/series
      - repo: libraries/documentaries/themes
  Live music & music videos:
    operations:
      assets_for_all: true
playlist_files:
  - repo: playlists/admin
  - repo: playlists/halloween
  - repo: playlists/movie_charts
  - repo: playlists/star_wars
