libraries:
  Movies:
    operations:
      assets_for_all: true
      content_rating_mapper:
        "gb/12A": "gb/12"
        None: "gb/Unrated"
      genre_mapper:
        Biography: Biopic
        "Sci-Fi": Science Fiction
        Martial Arts:
        Western:
    metadata_path:
      - repo: metadata/movies/Alien (1979) {tmdb-348}
      - repo: metadata/movies/Aliens (1986) {tmdb-679}
      - repo: metadata/movies/Ant-Man and the Wasp (2018) {tmdb-363088}
      - repo: metadata/movies/Avengers Endgame (2019) {tmdb-299534}
      - repo: metadata/movies/Black Widow (2021) {tmdb-497698}
      - repo: metadata/movies/Captain America The First Avenger (2011) {tmdb-1771}
      - repo: metadata/movies/Captain Marvel (2019) {tmdb-299537}
      - repo: metadata/movies/Doctor Strange (2016) {tmdb-284052}
      - repo: metadata/movies/Gerald's Game (2017) {tmdb-343674}
      - repo: metadata/movies/Guardians of the Galaxy Vol. 2 (2017) {tmdb-283995}
      - repo: metadata/movies/Hanna (2011) {tmdb-50456}
      - repo: metadata/movies/Iron Man 3 (2013) {tmdb-68721}
      - repo: metadata/movies/Minority Report (2002) {tmdb-180}
      - repo: metadata/movies/Pirates of the Caribbean Dead Man's Chest (2006) {tmdb-58}
      - repo: metadata/movies/Pirates of the Caribbean Dead Men Tell No Tales (2017) {tmdb-166426}
      - repo: metadata/movies/Spider-Man Far from Home (2019) {tmdb-429617}
      - repo: metadata/movies/Star Wars (1977) {tmdb-11}
      - repo: metadata/movies/Star Wars The Rise of Skywalker (2019) {tmdb-181812}
      - repo: metadata/movies/The Usual Suspects (1995) {tmdb-629}
      - repo: labelling/movies/content_rating/alcohol_and_tobacco
      - repo: labelling/movies/content_rating/discrimination
      - repo: labelling/movies/content_rating/disturbing_images
      - repo: labelling/movies/content_rating/injury_detail
      - repo: labelling/movies/content_rating/language
      - repo: labelling/movies/content_rating/nudity
      - repo: labelling/movies/content_rating/rude_humour
      - repo: labelling/movies/content_rating/sex
      - repo: labelling/movies/content_rating/theme
      - repo: labelling/movies/content_rating/threat_and_horror
      - repo: labelling/movies/content_rating/violence
      - repo: labelling/movies/editions
      - repo: labelling/movies/ownership
      - repo: labelling/movies/restrictions
      - repo: labelling/movies/series
      - repo: labelling/movies/sources
      - repo: labelling/shared/themes
      - repo: labelling/movies/themes
      - repo: libraries/shared/actors
      - repo: libraries/movies/directors
      - repo: libraries/movies/general
      - repo: libraries/shared/content_ratings
      - repo: libraries/shared/genres
      - repo: libraries/shared/series
      - repo: libraries/movies/series
      - repo: libraries/shared/themes
      - repo: libraries/movies/themes
      - repo: libraries/movies/charts
  TV shows:
    operations:
      assets_for_all: true
      content_rating_mapper:
        "gb/12A": "gb/12"
      genre_mapper:
        Biography: Biopic
        "Sci-Fi": Science Fiction
        Martial Arts:
        Western:
    metadata_path:
      - repo: labelling/tv_shows/content/drug_references
      - repo: labelling/tv_shows/content/drug_use
      - repo: labelling/tv_shows/content/gore
      - repo: labelling/tv_shows/content/horror
      - repo: labelling/tv_shows/content/injury_detail
      - repo: labelling/tv_shows/content/language
      - repo: labelling/tv_shows/content/nudity
      - repo: labelling/tv_shows/content/sex_references
      - repo: labelling/tv_shows/content/sex
      - repo: labelling/tv_shows/content/sexual_violence
      - repo: labelling/tv_shows/content/suicide
      - repo: labelling/tv_shows/content/threat
      - repo: labelling/tv_shows/content/violence
      - repo: labelling/tv_shows/ownership
      - repo: labelling/tv_shows/sources
      - repo: labelling/tv_shows/themes
      - repo: labelling/shared/themes
      - repo: libraries/shared/actors
      - repo: libraries/shared/content_ratings
      - repo: libraries/shared/genres
      - repo: libraries/shared/series
      - repo: libraries/shared/themes
      - repo: libraries/tv_shows/themes
  Stand-up comedy:
    operations:
      assets_for_all: true
    metadata_path:
      - repo: libraries/shared/content_ratings
  Short films:
    operations:
      assets_for_all: true
      content_rating_mapper:
        "gb/12A": "gb/12"
        None: "gb/Unrated"
      genre_mapper:
        Biography: Biopic
        "Sci-Fi": Science Fiction
        Martial Arts:
        Short:
        Western:
    metadata_path:
      - repo: metadata/short_films/2036 Nexus Dawn (2017) {tmdb-473072}
      - repo: metadata/short_films/2048 Nowhere to Run (2017) {tmdb-475759}
      - repo: metadata/short_films/Anima (2011) {tmdb-416185}
      - repo: metadata/short_films/Blade Runner Black Out 2022 (2017) {tmdb-475946}
      - repo: metadata/short_films/Marvel One-Shot A Funny Thing Happened on the Way to Thor's Hammer (2011) {tmdb-76535}
      - repo: metadata/short_films/Marvel One-Shot Agent Carter (2013) {tmdb-211387}
      - repo: metadata/short_films/Marvel One-Shot All Hail the King (2014) {tmdb-253980}
      - repo: metadata/short_films/Marvel One-Shot Item 47 (2012) {tmdb-119569}
      - repo: metadata/short_films/Marvel One-Shot The Consultant (2011) {tmdb-76122}
      - repo: metadata/short_films/Team Darryl (2018) {tmdb-505945}
      - repo: metadata/short_films/Team Thor Part 2 (2017) {tmdb-441829}
      - repo: labelling/short_films/ownership
      - repo: labelling/short_films/restrictions
      - repo: labelling/short_films/series
      - repo: labelling/short_films/sources
      - repo: labelling/short_films/themes
      - repo: libraries/shared/actors
      - repo: libraries/short_films/series
      - repo: libraries/short_films/themes
  Documentaries:
    operations:
      assets_for_all: true
      content_rating_mapper:
        "gb/12A": "gb/12"
      genre_mapper:
        Biography: Biopic
        "Sci-Fi": Science Fiction
        Martial Arts:
        Western:
    metadata_path:
      - repo: labelling/documentaries/themes
      - repo: libraries/shared/content_ratings
      - repo: libraries/shared/series
      - repo: libraries/documentaries/themes
  Live music & music videos:
    operations:
      assets_for_all: true
playlist_files:
  - repo: playlists/admin
  - repo: playlists/halloween
  - repo: playlists/movie_charts
  - repo: playlists/star_wars
