libraries:
  Movies:
    operations:
      assets_for_all: true
    metadata_path:
      - repo: metadata/movies/21 Grams (2003) {tmdb-470}
      - repo: metadata/movies/After Sex (2007) {tmdb-17097}
      - repo: metadata/movies/Alien (1979) {tmdb-348}
      - repo: metadata/movies/Alien Resurrection (1997) {tmdb-8078}
      - repo: metadata/movies/Alien3 (1992) {tmdb-8077}
      - repo: metadata/movies/Aliens (1986) {tmdb-679}
      - repo: metadata/movies/American Gangster (2007) {tmdb-4982}
      - repo: metadata/movies/Ant-Man and the Wasp (2018) {tmdb-363088}
      - repo: metadata/movies/Attack the Block (2011) {tmdb-59678}
      - repo: metadata/movies/Avengers Endgame (2019) {tmdb-299534}
      - repo: metadata/movies/Benedetta (2021) {tmdb-454527}
      - repo: metadata/movies/Black Widow (2021) {tmdb-497698}
      - repo: metadata/movies/Borat (2006) {tmdb-496}
      - repo: metadata/movies/Brightburn (2019) {tmdb-531309}
      - repo: metadata/movies/Calvary (2014) {tmdb-157832}
      - repo: metadata/movies/Captain America The First Avenger (2011) {tmdb-1771}
      - repo: metadata/movies/Captain Marvel (2019) {tmdb-299537}
      - repo: metadata/movies/Django Unchained (2012) {tmdb-68718}
      - repo: metadata/movies/Doctor Strange (2016) {tmdb-284052}
      - repo: metadata/movies/Doctor Strange in the Multiverse of Madness (2022) {tmdb-453395}
      - repo: metadata/movies/Don't Worry Darling (2022) {tmdb-619730}
      - repo: metadata/movies/Eternals (2021) {tmdb-524434}
      - repo: metadata/movies/Gerald's Game (2017) {tmdb-343674}
      - repo: metadata/movies/Gladiator (2000) {tmdb-98}
      - repo: metadata/movies/Goodnight, Mister Tom (1998) {tmdb-20546}
      - repo: metadata/movies/Guardians of the Galaxy Vol. 2 (2017) {tmdb-283995}
      - repo: metadata/movies/Halloween Kills (2021) {tmdb-610253}
      - repo: metadata/movies/Hanna (2011) {tmdb-50456}
      - repo: metadata/movies/Inception (2010) {tmdb-27205}
      - repo: metadata/movies/Iron Man 3 (2013) {tmdb-68721}
      - repo: metadata/movies/John Wick (2014) {tmdb-245891}
      - repo: metadata/movies/John Wick Chapter 2 (2017) {tmdb-324552}
      - repo: metadata/movies/John Wick Chapter 3 - Parabellum (2019) {tmdb-458156}
      - repo: metadata/movies/Leon The Professional (1994) {tmdb-101}
      - repo: metadata/movies/Malena (2000) {tmdb-10867}
      - repo: metadata/movies/Minority Report (2002) {tmdb-180}
      - repo: metadata/movies/Nope (2022) {tmdb-762504}
      - repo: metadata/movies/Pirates of the Caribbean At World's End (2007) {tmdb-285}
      - repo: metadata/movies/Pirates of the Caribbean Dead Man's Chest (2006) {tmdb-58}
      - repo: metadata/movies/Pirates of the Caribbean Dead Men Tell No Tales (2017) {tmdb-166426}
      - repo: metadata/movies/Pirates of the Caribbean On Stranger Tides (2011) {tmdb-1865}
      - repo: metadata/movies/Police Story 2 (1988) {tmdb-10753}
      - repo: metadata/movies/Return of the Jedi (1983) {tmdb-1892}
      - repo: metadata/movies/Rogue One A Star Wars Story {tmdb-330459}
      - repo: metadata/movies/Salt (2010) {tmdb-27576}
      - repo: metadata/movies/Shang-Chi and the Legend of the Ten Rings (2021) {tmdb-566525}
      - repo: metadata/movies/Shrek (2001) {tmdb-808}
      - repo: metadata/movies/Smile (2022) {tmdb-882598}
      - repo: metadata/movies/Solo A Star Wars Story {tmdb-348350}
      - repo: metadata/movies/Spider-Man 2 (2004) {tmdb-558}
      - repo: metadata/movies/Spider-Man Far from Home (2019) {tmdb-429617}
      - repo: metadata/movies/Spider-Man No Way Home (2021) {tmdb-634649}
      - repo: metadata/movies/Star Wars (1977) {tmdb-11}
      - repo: metadata/movies/Star Wars Episode I - The Phantom Menace (1999) {tmdb-1893}
      - repo: metadata/movies/Star Wars Episode II - Attack of the Clones (2002) {tmdb-1894}
      - repo: metadata/movies/Star Wars Episode III - Revenge of the Sith (2005) {tmdb-1895}
      - repo: metadata/movies/Star Wars Rebels Spark of Rebellion (2014) {tmdb-287663}
      - repo: metadata/movies/Star Wars Rebels The Siege of Lothal (2015) {tmdb-337755}
      - repo: metadata/movies/Star Wars The Clone Wars (2008) {tmdb-12180}
      - repo: metadata/movies/Star Wars The Force Awakens (2015) {tmdb-140607}
      - repo: metadata/movies/Star Wars The Last Jedi (2017) {tmdb-181808}
      - repo: metadata/movies/Star Wars The Rise of Skywalker (2019) {tmdb-181812}
      - repo: metadata/movies/Sucker Punch (2011) {tmdb-23629}
      - repo: metadata/movies/The Bank Job (2008) {tmdb-8848}
      - repo: metadata/movies/The Banshees of Inisherin (2022) {tmdb-674324}
      - repo: metadata/movies/The Empire Strikes Back (1980) {tmdb-1891}
      - repo: metadata/movies/The Girl with the Dragon Tattoo (2009) {tmdb-15472}
      - repo: metadata/movies/The Godfather (1972) {tmdb-238}
      - repo: metadata/movies/The Godfather Part II (1974) {tmdb-240}
      - repo: metadata/movies/The Godfather Part III (1990) {tmdb-242}
      - repo: metadata/movies/The Star Wars Holiday Special (1978) {tmdb-74849}
      - repo: metadata/movies/The Usual Suspects (1995) {tmdb-629}
      - repo: metadata/movies/The Wicker Man (1973) {tmdb-16307}
      - repo: metadata/movies/Thelma & Louise (1991) {tmdb-1541}
      - repo: metadata/movies/Thor Love and Thunder (2022) {tmdb-616037}
      - repo: metadata/movies/Trick 'r Treat (2007) {tmdb-23202}
      - repo: metadata/movies/Tropic Thunder (2008) {tmdb-7446}
      - repo: metadata/movies/Wedding Crashers (2005) {tmdb-9522}
      - repo: metadata/movies/Your Highness (2011) {tmdb-38319}
      - repo: labelling/movies/editions
      - repo: labelling/movies/content_rating/alcohol_and_tobacco
      - repo: labelling/movies/content_rating/discrimination
      - repo: labelling/movies/content_rating/disturbing_images
      - repo: labelling/movies/content_rating/drugs
      - repo: labelling/movies/content_rating/flashing_lights
      - repo: labelling/movies/content_rating/injury_detail
      - repo: labelling/movies/content_rating/language
      - repo: labelling/movies/content_rating/nudity
      - repo: labelling/movies/content_rating/rude_humour
      - repo: labelling/movies/content_rating/sex
      - repo: labelling/movies/content_rating/sexual_violence_and_threat
      - repo: labelling/movies/content_rating/suicide
      - repo: labelling/movies/content_rating/theme
      - repo: labelling/movies/content_rating/threat_and_horror
      - repo: labelling/movies/content_rating/violence
      - repo: labelling/movies/ownership
      - repo: labelling/movies/restrictions
      - repo: labelling/movies/series
      - repo: labelling/movies/sources
      - repo: labelling/shared/themes
      - repo: labelling/movies/themes
      - repo: libraries/shared/actors
      - repo: libraries/movies/directors
      - repo: libraries/movies/general
      - repo: libraries/shared/content_ratings
      - repo: libraries/shared/genres
      - repo: libraries/shared/series
      - repo: libraries/movies/series
      - repo: libraries/shared/themes
      - repo: libraries/movies/themes
      - repo: libraries/movies/charts
  TV shows:
    operations:
      assets_for_all: true
      content_rating_mapper:
        "gb/12A": "gb/12"
      genre_mapper:
        Biography: Biopic
        "Sci-Fi": Science Fiction
        Martial Arts:
        Western:
    metadata_path:
      - repo: labelling/tv_shows/content/drug_references
      - repo: labelling/tv_shows/content/drug_use
      - repo: labelling/tv_shows/content/gore
      - repo: labelling/tv_shows/content/horror
      - repo: labelling/tv_shows/content/injury_detail
      - repo: labelling/tv_shows/content/language
      - repo: labelling/tv_shows/content/nudity
      - repo: labelling/tv_shows/content/sex_references
      - repo: labelling/tv_shows/content/sex
      - repo: labelling/tv_shows/content/sexual_violence
      - repo: labelling/tv_shows/content/suicide
      - repo: labelling/tv_shows/content/threat
      - repo: labelling/tv_shows/content/violence
      - repo: labelling/tv_shows/ownership
      - repo: labelling/tv_shows/sources
      - repo: labelling/tv_shows/themes
      - repo: labelling/shared/themes
      - repo: libraries/shared/actors
      - repo: libraries/shared/content_ratings
      - repo: libraries/shared/genres
      - repo: libraries/shared/series
      - repo: libraries/shared/themes
      - repo: libraries/tv_shows/themes
  Stand-up comedy:
    operations:
      assets_for_all: true
    metadata_path:
      - repo: libraries/shared/content_ratings
  Short films:
    operations:
      assets_for_all: true
    metadata_path:
      - repo: metadata/short_films/2036 Nexus Dawn (2017) {tmdb-473072}
      - repo: metadata/short_films/2048 Nowhere to Run (2017) {tmdb-475759}
      - repo: metadata/short_films/Anima (2011) {tmdb-416185}
      - repo: metadata/short_films/Blade Runner Black Out 2022 (2017) {tmdb-475946}
      - repo: metadata/short_films/Laura Hasn't Slept (2020) {tmdb-689397}
      - repo: metadata/short_films/Marvel One-Shot A Funny Thing Happened on the Way to Thor's Hammer (2011) {tmdb-76535}
      - repo: metadata/short_films/Marvel One-Shot Agent Carter (2013) {tmdb-211387}
      - repo: metadata/short_films/Marvel One-Shot All Hail the King (2014) {tmdb-253980}
      - repo: metadata/short_films/Marvel One-Shot Item 47 (2012) {tmdb-119569}
      - repo: metadata/short_films/Marvel One-Shot The Consultant (2011) {tmdb-76122}
      - repo: metadata/short_films/Season's Greetings (1996) {tmdb-140149}
      - repo: metadata/short_films/Team Darryl (2018) {tmdb-505945}
      - repo: metadata/short_films/Team Thor Part 2 (2017) {tmdb-441829}
      - repo: labelling/short_films/ownership
      - repo: labelling/short_films/restrictions
      - repo: labelling/short_films/series
      - repo: labelling/short_films/sources
      - repo: labelling/short_films/themes
      - repo: libraries/shared/actors
      - repo: libraries/short_films/series
      - repo: libraries/short_films/themes
  Documentaries:
    operations:
      assets_for_all: true
      content_rating_mapper:
        "gb/12A": "gb/12"
      genre_mapper:
        Biography: Biopic
        "Sci-Fi": Science Fiction
        Martial Arts:
        Western:
    metadata_path:
      - repo: labelling/documentaries/themes
      - repo: libraries/shared/content_ratings
      - repo: libraries/shared/series
      - repo: libraries/documentaries/themes
  Live music & music videos:
    operations:
      assets_for_all: true
playlist_files:
  - repo: playlists/admin
  - repo: playlists/halloween
  - repo: playlists/movie_charts
  - repo: playlists/star_wars
