external_templates:
  - repo: templates/collection_type/Collectionless_Label

collections:
  Source__bluray:
    template:
      - name: TMDB source label
        source_type: bluray
    tmdb_movie:
      - 473072 # 2036: Nexus Dawn (2017)
      - 475759 # 2048: Nowhere to Run (2017)
      - 475946 # Blade Runner: Black Out 2022 (2017)
      - 58763 # God of Love (2010)
      - 689397 # Laura Hasn't Slept (2020)
      - 76535 # Marvel One-Shot: A Funny Thing Happened on the Way to Thor's Hammer (2011)
      - 211387 # Marvel One-Shot: Agent Carter (2013)
      - 253980 # Marvel One-Shot: All Hail the King (2014)
      - 119569 # Marvel One-Shot: Item 47 (2012)
      - 76122 # Marvel One-Shot: The Consultant (2011)
      - 140149 # Season's Greetings (1996)
      - 801109 # Shadowprowler (2021)
      - 505945 # Team Darryl (2018)
      - 441829 # Team Thor: Part 2 (2017)

  Source__download:
    template:
      - name: TMDB source label
        source_type: download
    tmdb_movie:
      - 416185 # Ánima (2011)

  Source__dvd:
    template:
      - name: TMDB source label
        source_type: dvd
    tmdb_movie:
      - 79089 # Assassin's Creed: Embers (2011)

  Source__vimeo:
    template:
      - name: TMDB source label
        source_type: vimeo
    tmdb_movie:
      - 416185 # Ánima (2011)
