external_templates:
  - repo: templates/collection_type/Collectionless_Label

collections:
  "Source: blu-ray":
    template:
      - name: Source label
        source: "blu-ray"
        title_list:
          - "2036: Nexus Dawn (2017)"
          - "2048: Nowhere to Run (2017)"
          - "Blade Runner: Black Out 2022 (2017)"
          - "Marvel One-Shot: All Hail the King (2014)"
          - "Marvel One-Shot: Item 47 (2012)"
          - "Marvel One-Shot: The Consultant (2011)"
          - Team Darryl (2018)

  "Source: download":
    template:
      - name: Source label
        source: "download"
        title_list:
          - "Ánima (2011)"

  "Source: Vimeo":
    template:
      - name: Source label
        source: "Vimeo"
        title_list:
          - "Ánima (2011)"
