external_templates:
  - repo: templates/collection_type/Collectionless_Label

collections:
  Source__bluray:
    template:
      - name: TMDB source label
        source_type: bluray
    plex_search:
      any:
        label:
          - 473072 # 2036: Nexus Dawn (2017)
          - 475759 # 2048: Nowhere to Run (2017)
          - 475946 # Blade Runner: Black Out 2022 (2017)
          - 76535 # Marvel One-Shot: A Funny Thing Happened on the Way to Thor's Hammer (2011)
          - 211387 # Marvel One-Shot: Agent Carter (2013)
          - 253980 # Marvel One-Shot: All Hail the King (2014)
          - 76122 # Marvel One-Shot: The Consultant (2011)

  Source__download:
    template:
      - name: TMDB source label
        source_type: download
    plex_search:
      any:
        label:
          - 416185 # Ánima (2011)

  Source__vimeo:
    template:
      - name: TMDB source label
        source_type: vimeo
    plex_search:
      any:
        label:
          - 416185 # Ánima (2011)

  "Source: blu-ray":
    template:
      - name: Source label
        source: "blu-ray"
        title_list:
          - Item 47 (2012)
          - Team Darryl (2018)
          - Team Thor (2016) 002
