external_templates:
  - repo: templates/collection_type/Collectionless_Label

collections:
  "Source: blu-ray":
    template:
      - name: Source label
        source: "blu-ray"
        title_list:
          - All Hail the King (2014)
          - "Blade Runner 2036: Nexus Dawn (2017)"
          - "Blade Runner 2048: Nowhere to Run (2017)"
          - "Blade Runner: Black Out 2022 (2017)"
          - Consultant (2011)
          - Funny Thing Happened on the Way to Thor's Hammer (2011)
          - Item 47 (2012)
          - Team Darryl (2018)
          - Team Thor (2016) 002

  "Source: download":
    template:
      - name: Source label
        source: "download"
        title_list:
          - "Ánima (2011)"

  "Source: Vimeo":
    template:
      - name: Source label
        source: "Vimeo"
        title_list:
          - "Ánima (2011)"
