external_templates:
  - repo: templates/collection_type/Collectionless_Label

collections:
  "Source: blu-ray":
    template:
      - name: Source label
        source: "blu-ray"
        title_list:
          - Big Bang Theory (2006)
          - Borgias (2011)
          - Community (2009) # Mix
          - Fawlty Towers (1975)
          - Friends (1994) # Mix
          - Game of Thrones (2011)
          - Gavin & Stacey (2007)
          - Haunting of Hill House (2018)
          - Heroes (2006)
          - "Hyperdimension Neptunia: The Animation (2013)"
          - Only Fools and Horses (1981) # Mix
          - Sherlock (2010)
          - Star Wars Rebels (2014)
          - "Star Wars: The Clone Wars (2008)"
          - True Blood (2008)
          - Westworld (2016)
          - Wire (2002)

  "Source: download":
    template:
      - name: Source label
        source: "download"
        title_list:
          - Carnival Row (2019)
          - Cyberpunk Edgerunners (2022)
          - Euphoria (2019)
          - Final Space (2018)
          - Man in the High Castle (2015)
          - Marvelous Mrs Maisel (2017)
          - Resident Evil (2022)
          - Wheel of Time (2021)
          - White Lotus (2021)

  "Source: dvd":
    template:
      - name: Source label
        source: "dvd"
        title_list:
          - Black Books (2000)
          - Buffy the Vampire Slayer (1997)
          - Dad's Army (1968)
          - Frankie Boyle's Tramadol Nights (2010)
          - Friends (1994) # Mix
          - IT Crowd (2006)
          - Lenny Henry in Pieces (2000)
          - Only Fools and Horses (1981) # Mix
          - Open All Hours (1976)
          - Porridge (1974)
          - Robot Chicken (2001)
          - Scrubs (2001)
          - Spaced (1999)
          - That 70s Show (1998)

  "Source: Amazon Prime":
    template:
      - name: Source label
        source: "Amazon Prime"
        title_list:
          - Carnival Row (2019)
          - Euphoria (2019)
          - Man in the High Castle (2015)
          - Marvelous Mrs Maisel (2017)
          - Wheel of Time (2021)
          - White Lotus (2021)

  "Source: Netflix":
    template:
      - name: Source label
        source: "Netflix"
        title_list:
          - Community (2009) # Mix
          - Cyberpunk Edgerunners (2022)
          - Final Space (2018)
          - Resident Evil (2022)
