external_templates:
  - repo: templates/collection_type/Collectionless_Label

collections:
  Source__bluray:
    template:
      - name: TMDB source label
        source_type: bluray
    plex_search:
      any:
        label:
          - ID__000363088A # Ant-Man and the Wasp
          - ID__000299534A # Avengers: Endgame
          - ID__000001771A # Captain America: The First Avenger
          - ID__000299537A # Captain Marvel
          - ID__000284052A # Doctor Strange
          - ID__000283995A # Guardians of the Galaxy Vol. 2
          - ID__000068721A # Iron Man 3 (2013)
          - ID__000000058A # Pirates of the Caribbean: Dead Man's Chest (2006)
          - ID__000166426A # Pirates of the Caribbean: Dead Men Tell No Tales
          - ID__000634649A # Spider-Man: Far from Home
          - ID__000000011D # Star Wars: Episode IV - A New Hope [Blu-ray cut]
          - ID__000000629A # The Usual Suspects

  Source__download:
    template:
      - name: TMDB source label
        source_type: download
    plex_search:
      any:
        label:
          - ID__000000011B # Star Wars: Episode IV - A New Hope [Special edition]
          - ID__000000011E # Star Wars: Episode IV - A New Hope [Despecialized edition]
          - ID__000000011F # Star Wars: Episode IV - A New Hope [Project 4K77]

  Source__dvd:
    template:
      - name: TMDB source label
        source_type: dvd
    plex_search:
      any:
        label:
          - ID__000000011A # Star Wars: Episode IV - A New Hope [Theatrical cut]
          - ID__000000011C # Star Wars: Episode IV - A New Hope [DVD cut]

  "Source: blu-ray":
    template:
      - name: Source label
        source: "blu-ray"
        title_list:
          - 4.3.2.1 (2010)
          - 28 Days Later (2002) 001
          - 28 Days Later (2002) 002
          - 300 (2007) 001
          - 300 (2007) 002
          - Alien (1979) 001 1979 Theatrical cut
          - Alien (1979) 001 2003 Director's cut
          - Alien (1979) 002 1986 Theatrical cut
          - Alien (1979) 002 1990 Special Edition
          - Alien (1979) 003A
          - Alien (1979) 003B
          - Alien (1979) 004A
          - Alien (1979) 004B
          - "Alien: Covenant (2017)"
          - Amazing Spider-Man (2012) 002
          - American Beauty (1999)
          - American Gangster (2007) 001A
          - American Gangster (2007) 001B
          - Anchorman (2004) 001
          - Angel-A (2005)
          - Ant-Man (2015) 001
          - Avengers (2012) 001
          - Avengers (2012) 002
          - Avengers (2012) 003
          - Back to the Future (1985) 001
          - Back to the Future (1985) 002
          - Back to the Future (1985) 003
          - Basic Instinct (1992) 001
          - Batman (1989) 001
          - Batman (1989) 002
          - Batman (1989) 003
          - Batman (1989) 004
          - Batman (2022) 001
          - Batman Begins (2005)
          - Beautiful Mind (2001)
          - Benedetta (2021)
          - BFG (2016)
          - Birds (1963)
          - Birds of Prey (2020)
          - Black Panther (2018) 001
          - Black Swan (2010)
          - Blade Runner (1982) 001 2007 Final Cut
          - Blade Runner (1982) 002
          - Blades of Glory (2007)
          - Blair Witch Project (1999) 001
          - Blue is the Warmest Colour (2013)
          - Bone Collector (1999)
          - Bone Tomahawk (2015)
          - Boogie Nights (1997)
          - Book of Eli (2010)
          - Bugsy Malone (1976)
          - Cabin in the Woods (2012)
          - Captain America (2011) 001
          - Captain America (2011) 002
          - Captain America (2011) 003
          - Casino (1995)
          - Casino Royale (2006)
          - Casper (1995)
          - Che (2008) 001
          - Che (2008) 002
          - Chloe (2009)
          - Choke (2008)
          - Clash of the Titans (1981)
          - Dad's Army (1971) 001
          - Dark Knight (2008)
          - Dark Knight Rises (2012)
          - Departed (2006)
          - Devil's Advocate (1997)
          - Devil's Backbone (2001)
          - Diamonds Are Forever (1971)
          - Die Another Day (2002)
          - Die Hard (1988) 001
          - Disappearance of Alice Creed (2010)
          - District 9 (2009)
          - Doctor Sleep (2019)
          - "Dodgeball: A True Underdog Story (2004)"
          - Dolce Vita (1960)
          - Dr. No (1962)
          - Dracula (1992)
          - Dreamers (2003)
          - Due Date (2010)
          - Dune (2021) 001
          - Elf (2003)
          - Emmanuelle (1974) 001
          - Ex Machina (2015)
          - Faculty (1998)
          - Family Plot (1976)
          - Farewell, My Queen (2012)
          - Favourite (2018)
          - Fifth Element (1997)
          - Fight Club (1999)
          - For Your Eyes Only (1981)
          - French Dispatch (2021)
          - Frenzy (1972)
          - From Russia with Love (1963)
          - Gandhi (1982)
          - Gangs of New York (2002)
          - Get Him to the Greek (2010)
          - Gia (1998)
          - Gilda (1946)
          - Gladiator (2000)
          - Goldfinger (1964)
          - GoldenEye (1995)
          - Goodfellas (1990)
          - Great Muppet Caper (1981)
          - Green Mile (1999)
          - Guardians of the Galaxy (2014) 001
          - Halloween (1978) 001
          - Halloween (1978) 002
          - Halloween (1978) 004
          - Halloween (1978) 005
          - Halloween (1978) 006
          - Halloween (1978) 007
          - Halloween (1978) 008
          - Halloween (2018) 001
          - Halloween (2018) 002
          - Hanna (2011)
          - Harry Brown (2009)
          - Harry Potter (2001) 001
          - Harry Potter (2001) 002
          - Harry Potter (2001) 003
          - Harry Potter (2001) 004
          - Harry Potter (2001) 005
          - Harry Potter (2001) 006
          - Harry Potter (2001) 007
          - Harry Potter (2001) 008
          - Her (2014)
          - Hercules (1997)
          - Hobbit (2012) 001
          - Hobbit (2012) 002
          - Hobbit (2012) 003
          - Hobo with a Shotgun (2011)
          - Holiday (2006)
          - Hook (1991)
          - Hot Fuzz (2007)
          - Hot Tub Time Machine (2010)
          - Hunger Games (2012) 001
          - Hunger Games (2012) 002
          - Hunger Games (2012) 003
          - Hunger Games (2012) 004
          - I Spit on Your Grave (1978)
          - Identity (2003)
          - "Import/Export (2007)"
          - Incredible Hulk (2008) 001
          - Incredibles (2004) 001
          - Indiana Jones (1981) 001
          - Indiana Jones (1981) 002
          - Indiana Jones (1981) 003
          - Indiana Jones (1981) 004
          - Inglourious Basterds (2009)
          - Inhale (2010)
          - Invisible Man (2020)
          - Iron Man (2008) 001
          - Iron Man (2008) 002
          - IT (2017) 001
          - IT (2017) 002
          - It Follows (2015)
          - Jaws (1975) 001
          - Jojo Rabbit (2019)
          - Jurassic Park (1993) 001
          - Jurassic Park (1993) 002
          - Jurassic Park (1993) 003
          - Jurassic World (2015) 001
          - Jurassic World (2015) 002
          - Kick-Ass (2010) 001
          - Kick-Ass (2010) 002
          - Kingsman (2014) 001
          - Knives Out (2019)
          - Knock Knock (2015)
          - Kung Fu Hustle (2004)
          - "Lara Croft: Tomb Raider (2001) 001"
          - Last Night in Soho (2021)
          - Leave No Trace (2018)
          - Lego Movie (2014) 001
          - Lego Movie (2014) 002
          - Leon The Professional (1994) 001
          - Licence to Kill (1989)
          - Lion King (1994) 001
          - Live and Let Die (1973)
          - Living Daylights (1987)
          - Look of Love (2013)
          - Lord of the Rings (2001) 001B
          - Lord of the Rings (2001) 002B
          - Lord of the Rings (2001) 003B
          - Lost Girls and Love Hotels (2020)
          - Lucy (2014)
          - Machete (2010) 001
          - Machete (2010) 002
          - Malena (2000) 001A
          - Malena (2000) 001B
          - Man on Fire (2004)
          - Man Who Knew Too Much (1956)
          - Man with the Golden Gun (1974)
          - Marnie (1964)
          - Martha Marcy May Marlene (2011)
          - Matrix (1999) 001
          - Matrix (1999) 002
          - Matrix (1999) 003
          - Men in Black (1997) 001
          - Men in Black (1997) 002
          - Minority Report (2002)
          - Miracle on 34th Street (1994)
          - Miss Sloane (2016)
          - Mist (2007)
          - Monster (2004)
          - Moonraker (1979)
          - Mr and Mrs Smith (2005)
          - Mummy (1999) 001
          - Mummy (1999) 002
          - Muppet Christmas Carol (1992)
          - Muppets from Space (1999)
          - Muppet Treasure Island (1996)
          - Mystic River (2003)
          - Naked Gun (1988) 001
          - Naked Gun (1988) 002 The Smell of Fear
          - Naked Gun (1988) 003 The Final Insult
          - National Treasure (2004) 001
          - National Treasure (2004) 002
          - Nativity! (2009) 001
          - No Country for Old Men (2007)
          - No Time to Die (2021)
          - Ocean's 11 (2001) 001
          - Ocean's 11 (2001) 002
          - Ocean's 11 (2001) 003
          - Octopussy (1983)
          - Old School (2003)
          - On Her Majesty's Secret Service (1969)
          - One Flew Over the Cuckoo's Nest (1975)
          - Pan's Labyrinth (2006)
          - Parasite (2019)
          - Paul (2011)
          - Pet Sematary (2019)
          - Pirates of the Caribbean (2003) 001
          - Planet Terror (2007)
          - Platoon (1986)
          - Police Story (1985) 001
          - Police Story (1985) 002A
          - Police Story (1985) 002B
          - Predator (1987) 001
          - Predator (1987) 002
          - Predator (1987) 003
          - Prometheus (2012)
          - Promising Young Woman (2020)
          - Psycho (1960)
          - Pulp Fiction (1994)
          - Q (2011)
          - Quantum of Solace (2008)
          - Ready or Not (2019)
          - Rear Window (1954)
          - Red Sparrow (2018)
          - Reservoir Dogs (1992)
          - Resident Evil (2002) 001
          - Resident Evil (2002) 002
          - Resident Evil (2002) 003
          - Resident Evil (2002) 004
          - Resident Evil (2002) 005
          - Resident Evil (2002) 006
          - Resident Evil (2021) 001
          - "Rogue One: A Star Wars Story (2016)"
          - Rope (1948)
          - Room in Rome (2010)
          - Rules of Engagement (2000)
          - Saboteur (1942)
          - Salt (2010) 001A
          - Salt (2010) 001B
          - Salt (2010) 001C
          - "Santa Claus: The Movie (1985)"
          - Saw (2004) 001
          - Saw (2004) 002
          - Saw (2004) 003
          - Saw (2004) 004
          - Saw (2004) 005
          - Saw (2004) 006
          - Saw (2004) 007
          - Scary Movie (2000) 001
          - Scary Movie (2000) 002
          - Scary Movie (2000) 003
          - Schindler's List (1993)
          - Scorpion King (2002) 001
          - Scott Pilgrim vs. the World (2010)
          - Scream (1996) 001
          - Scream (1996) 002
          - Scream (1996) 003
          - Scream (1996) 004
          - Scream (1996) 005
          - Secret Life of Pets (2016) 001
          - Seven (1995)
          - Shadow of a Doubt (1943)
          - Shame (2011)
          - Shank (2010)
          - Shaun of the Dead (2004)
          - Shawshank Redemption (1994)
          - Sherlock Holmes (2009) 001
          - Sherlock Holmes (2009) 002
          - Shining (1980)
          - Shutter Island (2010)
          - Silence of the Lambs (1991)
          - Silent Hill (2006) 001
          - Sin City (2005) 001
          - Sin City (2005) 002
          - Single Man (2009)
          - Skyfall (2012)
          - Sleeping Beauty (2011)
          - "Solo: A Star Wars Story (2018)"
          - Species (1995) 001
          - Spectre (2015)
          - Spider-Man (2002) 002A
          - Spider-Man (2002) 002B 2.1
          - Spider-Man (2017) 001
          - Spiral (2021)
          - Spirit (2008)
          - Spy Who Loved Me (1977)
          - Star Trek (2009) 001
          - Star Wars 001 (1999) 2011
          - Star Wars 002 (2002) 2011
          - Star Wars 003 (2005) 2011
          - Star Wars 005 (1980) 2011
          - Star Wars 006 (1983) 2011
          - Star Wars 007 (2015)
          - Star Wars 008 (2017)
          - Star Wars 009 (2019)
          - Star Wars Rebels (2014) 001
          - Star Wars Rebels (2014) 002
          - "Star Wars: The Clone Wars (2008)"
          - Sucker Punch (2011) 001A
          - Sucker Punch (2011) 001B
          - Suicide Squad (2021)
          - Super 8 (2011)
          - Taken (2008) 001
          - Taxi Driver (1976)
          - There Will Be Blood (2008)
          - Thing (1982)
          - Thor (2011) 001
          - Thor (2011) 002
          - Thor (2011) 003
          - Thunderball (1965)
          - Titanic (1997)
          - Tomorrow Never Dies (1997)
          - Topaz (1969)
          - Torn Curtain (1966)
          - Toy Story (1995) 001
          - Toy Story (1995) 002
          - Toy Story (1995) 003
          - Train to Busan (2016)
          - Transformers (2007) 001
          - Transformers (2007) 002
          - Transformers (2007) 003
          - Troy (2004) 001B
          - Trouble with Harry (1955)
          - True Grit (2010)
          - Tucker and Dale vs. Evil (2010)
          - Tuxedo (2002)
          - Tyrannosaur (2011)
          - Uncharted (2022) 001
          - Under the Skin (2014)
          - Vertigo (1958)
          - View to a Kill (1985)
          - War Dogs (2016)
          - Watchmen (2009)
          - What the Peeper Saw (1972)
          - What We Do in the Shadows (2014)
          - Wicker Man (1973) 001A
          - Wicker Man (1973) 001B
          - Wicker Man (1973) 001C
          - Witch (2015)
          - Wolf of Wall Street (2013)
          - Wonder Woman (2017) 001
          - Wonder Woman (2017) 002
          - World's End (2013)
          - World is Not Enough (1999)
          - X (2022)
          - You Only Live Twice (1967)
          - Zack and Miri Make a Porno (2008)
          - Zero Dark Thirty (2013)
          - Zombieland (2009) 001
          - Zoolander (2001) 001

  "Source: download":
    template:
      - name: Source label
        source: "download"
        title_list:
          - Blonde (2022)
          - Deep Water (2022)
          - Gerald's Game (2017)
          - Grand Central (2013)
          - Jolene (2008)
          - Lie (2020)
          - Nocturne (2020)
          - Palm Springs (2020)
          - Sergio (2020)
          - Songbird (2020)
          - Star Wars 005 (1980) 1997
          - Star Wars 005 (1980) 2016
          - Star Wars 006 (1983) 1997
          - Star Wars 006 (1983) 2016
          - Star Wars 006 (1983) 2019
          - Star Wars Holiday Special (1978)
          - Voyeurs (2021)
          - Wasp Network (2020)

  "Source: Amazon Prime":
    template:
      - name: Source label
        source: "Amazon Prime"
        title_list:
          - Deep Water (2022)
          - Grand Central (2013)
          - Lie (2020)
          - Nocturne (2020)
          - Palm Springs (2020)
          - Songbird (2020)
          - Voyeurs (2021)

  "Source: dvd":
    template:
      - name: Source label
        source: "dvd"
        title_list:
          - After Sex (2007)
          - Anything For Her (2008)
          - "Assassin's Creed: Embers (2011)"
          - Aventure (2009)
          - Baise-moi (2000)
          - Big Nothing (2006)
          - Bitch Slap (2009)
          - Black Dahlia (2006)
          - Black Dynamite (2010)
          - Boogie Woogie (2009)
          - Boss'n Up (2005)
          - Calendar Girls (2003)
          - Card Player (2004)
          - Cashback (2007)
          - Cathy Come Home (1966)
          - Chicken Run (2000)
          - Complicity (2000)
          - Cool Runnings (1993)
          - Corrina, Corrina (1994)
          - Dressage (1986)
          - Exterminating Angels (2006)
          - Fatal Instinct (1993)
          - Fausto 5.0 (2001)
          - Freaked (1994)
          - Hard Boiled (1992)
          - Head in the Clouds (2004)
          - High Fidelity (2000)
          - Hunger (2008)
          - I Am Curious (1963) 001
          - I Am Curious (1963) 002
          - Juan of the Dead (2012)
          - Ma mere (2004)
          - Mafia! (1998)
          - Match Point (2005)
          - Mexican (2001)
          - Mighty Aphrodite (1995)
          - Night at the Roxbury (1998)
          - Novo (2002)
          - "Ong-Bak: Muay Thai Warrior (2003)"
          - Remember the Titans (2000)
          - Room (2003)
          - School of Rock (2003)
          - "Scooby-Doo 2: Monsters Unleashed (2004)"
          - Secretary (2002)
          - Sliver (1993)
          - "South Park: Bigger, Longer & Uncut (1999)"
          - Star Wars 001 (1999) 2001
          - Star Wars 002 (2002) 2002B
          - Star Wars 003 (2005) 2005B
          - Star Wars 005 (1980) 1980
          - Star Wars 005 (1980) 2004
          - Star Wars 006 (1983) 1983
          - Star Wars 006 (1983) 2004
          - Superstar (1999)
          - Sweet Karma (2010)
          - Tenacious D in the Pick of Destiny (2006)
          - Wake Up, Ron Burgundy (2004)
          - Whole Nine Yards (2000)
          - Wind that Shakes the Barley (2006)

  "Source: Netflix":
    template:
      - name: Source label
        source: "Netflix"
        title_list:
          - Blonde (2022)
          - Gerald's Game (2017)
          - Sergio (2020)
          - Wasp Network (2020)
