external_templates:
  - repo: templates/collection_type/Collectionless_Label

collections:
  Source__bluray:
    template:
      - name: TMDB source label
        source_type: bluray
    plex_search:
      any:
        label:
          - ID__000100088A__S01E01 # The Last of Us (2023)
