external_templates:
  - repo: templates/collection_type/Collectionless_Label

collections:
  Episode Source__bluray:
    template:
      - name: TMDB source label
        source_type: bluray
    plex_search:
      any:
        label:
          - ID__000100088A__S01E01 # The Last of Us (2023)
          - ID__000100088A__S01E02
          - ID__000100088A__S01E03
          - ID__000046648A__S01E01 # True Detective (2014)
          - ID__000046648A__S01E02
          - ID__000046648A__S01E03
          - ID__000046648A__S01E04
          - ID__000046648A__S01E05
          - ID__000046648A__S01E06
