external_templates:
  - repo: templates/collection_type/Collectionless_Label

collections:
  "Source: blu-ray":
    template:
      - name: Source label
        source: "blu-ray"
        title_list:
          - 4.3.2.1 (2010)
          - 300 (2007) 001
          - 300 (2007) 002
          - Alien (1979) 001 1979 Theatrical cut
          - Alien (1979) 001 2003 Director's cut
          - Alien (1979) 002 1986 Theatrical cut
          - Alien (1979) 002 1990 Special Edition
          - Alien (1979) 003A
          - Alien (1979) 003B
          - Alien (1979) 004A
          - Alien (1979) 004B
          - "Alien: Covenant (2017)"
          - Amazing Spider-Man (2012) 002
          - American Beauty (1999)
          - American Gangster (2007) 001A
          - American Gangster (2007) 001B
          - Anchorman (2004) 001
          - Angel-A (2005)
          - Ant-Man (2015) 001
          - Avengers (2012) 001
          - Avengers (2012) 002
          - Avengers (2012) 003
          - Back to the Future (1985) 001
          - Back to the Future (1985) 002
          - Back to the Future (1985) 003
          - Basic Instinct (1992) 001
          - Batman (1989) 001
          - Batman (1989) 002
          - Batman (1989) 003
          - Batman (1989) 004
          - Batman (2022) 001
          - Batman Begins (2005)
          - Beautiful Mind (2001)
          - BFG (2016)
          - Birds (1963)
          - Birds of Prey (2020)
          - Black Panther (2018) 001
          - Black Swan (2010)
          - Blade Runner (1982) 001 2007 Final Cut
          - Blade Runner (1982) 002
          - Blades of Glory (2007)
          - Blue is the Warmest Colour (2013)
          - Boogie Nights (1997)
          - Captain America (2011) 002
          - Captain America (2011) 003
          - Casino (1995)
          - Casino Royale (2006)
          - Che (2008) 001
          - Che (2008) 002
          - Chloe (2009)
          - Clash of the Titans (1981)
          - Dad's Army (1971) 001
          - Dark Knight (2008)
          - Dark Knight Rises (2012)
          - Departed (2006)
          - Diamonds Are Forever (1971)
          - Die Hard (1988) 001
          - Disappearance of Alice Creed (2010)
          - District 9 (2009)
          - Doctor Sleep (2019)
          - Dr. No (1962)
          - Dreamers (2003)
          - Dune (2021) 001
          - Ex Machina (2015)
          - Family Plot (1976)
          - Farewell, My Queen (2012)
          - Favourite (2018)
          - Fifth Element (1997)
          - Fight Club (1999)
          - For Your Eyes Only (1981)
          - French Dispatch (2021)
          - From Russia with Love (1963)

  "Source: download":
    template:
      - name: Source label
        source: "download"
        title_list:
          - Deep Water (2022)
          - Grand Central (2013)
          - Jolene (2008)
          - Lie (2020)
          - Nocturne (2020)
          - Palm Springs (2020)
          - Songbird (2020)
          - Star Wars 004 (1977) 1997
          - Star Wars 004 (1977) 2016
          - Star Wars 004 (1977) 2018
          - Star Wars 005 (1980) 1997
          - Star Wars 005 (1980) 2016
          - Star Wars 006 (1983) 1997
          - Star Wars 006 (1983) 2016
          - Star Wars 006 (1983) 2019
          - Voyeurs (2021)

  "Source: Amazon Prime":
    template:
      - name: Source label
        source: "Amazon Prime"
        title_list:
          - Deep Water (2022)
          - Grand Central (2013)
          - Lie (2020)
          - Nocturne (2020)
          - Palm Springs (2020)
          - Songbird (2020)
          - Voyeurs (2021)

  "Source: dvd":
    template:
      - name: Source label
        source: "dvd"
        title_list:
          - After Sex (2007)
          - Anything For Her (2008)
          - "Assassin's Creed: Embers (2011)"
          - Aventure (2009)
          - Baise-moi (2000)
          - Big Nothing (2006)
          - Bitch Slap (2009)
          - Black Dahlia (2006)
          - Black Dynamite (2010)
          - Boogie Woogie (2009)
          - Boss'n Up (2005)
          - Calendar Girls (2003)
          - Card Player (2004)
          - Cashback (2007)
          - Cathy Come Home (1966)
          - Chicken Run (2000)
          - Complicity (2000)
          - Cool Runnings (1993)
          - Corrina, Corrina (1994)
          - Dressage (1986)
          - Exterminating Angels (2006)
          - Fausto 5.0 (2001)
          - Head in the Clouds (2004)
          - High Fidelity (2000)
          - Hunger (2008)
          - I Am Curious (1963) 001
          - I Am Curious (1963) 002
          - I Spit on Your Grave (1978)
          - Juan of the Dead (2012)
          - Ma mere (2004)
          - Match Point (2005)
          - Mexican (2001)
          - Mighty Aphrodite (1995)
          - Monster (2004)
          - Muppet Treasure Island (1996)
          - Night at the Roxbury (1998)
          - Novo (2002)
          - "Ong-Bak: Muay Thai Warrior (2003)"
          - Remember the Titans (2000)
          - Room (2003)
          - School of Rock (2003)
          - "Scooby-Doo 2: Monsters Unleashed (2004)"
          - Secretary (2002)
          - Sliver (1993)
          - "South Park: Bigger, Longer & Uncut (1999)"
          - Star Wars 001 (1999) 2001
          - Star Wars 002 (2002) 2002B
          - Star Wars 003 (2005) 2005B
          - Star Wars 004 (1977) 1977
          - Star Wars 004 (1977) 2004
          - Star Wars 005 (1980) 1980
          - Star Wars 005 (1980) 2004
          - Star Wars 006 (1983) 1983
          - Star Wars 006 (1983) 2004
          - Superstar (1999)
          - Sweet Karma (2010)
          - Tenacious D in the Pick of Destiny (2006)
          - Wake Up, Ron Burgundy (2004)
          - Whole Nine Yards (2000)
          - Wind that Shakes the Barley (2006)
